table DateTable
	lineageTag: acc45036-ec88-4c6d-a8a2-f1d35e634196
	dataCategory: Time

	column Dates
		dataType: dateTime
		isKey
		formatString: Short Date
		lineageTag: 0e18bd86-45fa-46c6-8b15-22ff6b9919bf
		summarizeBy: none
		sourceColumn: Dates

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Year
		dataType: int64
		formatString: 0
		lineageTag: 2bc51fb8-0362-435b-8a6c-dbc05b9b3f1e
		summarizeBy: sum
		sourceColumn: Year

		annotation SummarizationSetBy = Automatic

	column Month
		dataType: int64
		formatString: 0
		lineageTag: 66ff23fc-cc18-4c8f-a41f-87d406b0ed93
		summarizeBy: sum
		sourceColumn: Month

		annotation SummarizationSetBy = Automatic

	column LongDate
		dataType: dateTime
		formatString: Long Date
		lineageTag: b6d1fcea-5f9d-423e-9b2a-8eea65c31a43
		summarizeBy: none
		sourceColumn: LongDate

		changedProperty = DataType

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Season
		dataType: string
		lineageTag: 6b83528b-d1ec-41f6-ae20-8dad98aebd76
		summarizeBy: none
		sourceColumn: Season

		annotation SummarizationSetBy = Automatic

	column SeasonIndex =
			
			IF(
			    MONTH('DateTable'[Dates]) >= 7,
			    YEAR('DateTable'[Dates]),
			    YEAR('DateTable'[Dates]) - 1
			)
		lineageTag: 7fab3b00-0031-4464-8974-f97309459ac1
		summarizeBy: sum

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition DateTable = m
		mode: import
		source = ```
				let
				    Source = List.Dates(
				     StartDate, 
				     Duration.Days( EndDate - StartDate ) + 1, // Number of steps
				     #duration( 1, 0, 0, 0 )
				  ),
				    #"Converted to Table" = Table.FromList(Source, Splitter.SplitByNothing(), null, null, ExtraValues.Error),
				    #"Changed Type" = Table.TransformColumnTypes(#"Converted to Table",{{"Column1", type date}}),
				    #"Renamed Columns" = Table.RenameColumns(#"Changed Type",{{"Column1", "Dates"}}),
				    #"Inserted Year" = Table.AddColumn(#"Renamed Columns", "Year", each Date.Year([Dates]), Int64.Type),
				    #"Inserted Month" = Table.AddColumn(#"Inserted Year", "Month", each Date.Month([Dates]), Int64.Type),
				    #"Added Custom" = Table.AddColumn(#"Inserted Month", "LongDate", each Date.ToText([Dates],"dd MMMM yyyy")),
				    #"Added Custom1" = Table.AddColumn(#"Added Custom", "Season", each Table.AddColumn(#"Added Custom", "Season", each let
				    SeasonStart = if Date.Month([Dates]) >= 7
				                  then Date.Year([Dates])
				                  else Date.Year([Dates]) - 1
				in
				    Text.End(Text.From(SeasonStart), 2) & "/" &
				    Text.End(Text.From(SeasonStart + 1), 2))),
				    #"Removed Columns" = Table.AddColumn(#"Added Custom", "Season", each let
				    SeasonStart = if Date.Month([Dates]) >= 7
				                  then Date.Year([Dates])
				                  else Date.Year([Dates]) - 1
				in
				    Text.End(Text.From(SeasonStart), 2) & "/" &
				    Text.End(Text.From(SeasonStart + 1), 2))
				in
				    #"Removed Columns"
				```

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

