table player_latest_market_value
	lineageTag: 86220c56-8b2a-4603-8f22-e29446f6494d

	column player_id
		dataType: int64
		formatString: 0
		lineageTag: 12a4003a-3a84-4a57-9f68-b87cca2e4c41
		summarizeBy: none
		sourceColumn: player_id

		annotation SummarizationSetBy = Automatic

	column date_unix
		dataType: dateTime
		formatString: Long Date
		lineageTag: c355c2e7-c6e4-4939-bb7c-0e8501b893fb
		summarizeBy: none
		sourceColumn: date_unix

		variation Variation
			isDefault
			relationship: b1fc5ad7-a9f2-4bb7-999e-24ba5ab21e2a
			defaultHierarchy: LocalDateTable_c7ac97a8-6cac-4acb-82d6-bfe0f6d26860.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column value
		dataType: int64
		formatString: 0
		lineageTag: c92efc0d-9d68-4946-97d1-56a2dcf66ba9
		summarizeBy: sum
		sourceColumn: value

		annotation SummarizationSetBy = Automatic

	partition player_latest_market_value = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("C:\Users\JIGNESHHHHH\Documents\SQL\Datasets\football\player_latest_market_value.csv"),[Delimiter=",", Columns=3, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"player_id", Int64.Type}, {"date_unix", type date}, {"value", Int64.Type}})
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table

